export const reasonsToLove = [
  "Cozinha doces maravilhosos!",
  "Super amorosa com quem gosta",
  "É muito fofa quando fica imersa em algo que gosta, como os manhwas",
  "Simplesmente uma gostosa dá vontade de morder cada cm da coxa de bonita",
  "Se preocupa com os amigos e com a familia",
  "Mãe do cachorro mais fofo do mundo te amo Esnupi",
  "Tem o cabelo mais lindo do mundo",
  "O gosto musical é impecavel ♡ I'm gonna love you til day I die babe",
  "Extremamente estilosa, no meu coração você é modelo",
  "Sempre dá apoio moral e emocional quando os outros precisam",
  "Me inspira a ser melhor, quero ser alguem legal para você Mei, quero te acompanhar na sua vida (se você deixar é claro)",
  "Tem um jeito lindo e profundo de amar os outros",
  "Joga genshin muito bem !! quer ser meu duo em outros games?",
  "Corajosa e forte, passa segurança às pessoas",
  "Aposto 1000 reais que minha mãe ia gostar dela",
  "Aposto 1000 reais que meus gatos iam gostar dela",
  "Sempre respeita o espaço pessoal dos outros",
  "É divertido passar tempo de qualidade com ela",
  "Não julga minhas esquisitices",
  "Tem os olhos mais lindos do mundo me derreto quando vejo em fotos mas queria vê ao vivo",
  "Engual a Mitsuki Koga",
  "Ajuda com os links de mangás/manhwas",
  "Sempre coloca os melhores edits na timeline",
  "Sempre é franca com as coisas que gosta e não gosta",
  "Primeira pessoa NO MUNDO que conheci que gosta de vocaloid",
  "Tem as melhores reações quando gosta de algo, consigo sentir a empolgação daqui de São Paulo",
  "A primeira mulher morcego a andar pela terra",
  "Tem o rosto mais lindo do mundo merecia uma pintura",
  "DESENHA BEM DEMAISSSS",
  "É >A< lésbica (autoexplicativo)",
  "Compartilha os melhores memes",
  "É uma boa confidente",
  "Com certeza me ajudaria a por fogo nas igrejas kkkkk",
  "É a pessoa mais amável do mundo",
  "Bruxa & gostosa, eu deitaria em cima de um pentagrama de sangue por ela facilmente",
  "É a última romântica do mundo",
  "Tem uma franjinha super charmosa",
  "Cheia de piercings estilosos na orelha",
  "Ama ser mimada e isso é FOFO",
  "Tem a voz mais gostosa de ouvir do mundo inteiro",
  "Tem um sotaque carioca delicia dms",
  "O cabelo dela é preto e é igual olhar pro céu limpo de noite",
  "Tem o nariz lindo mesmo após dar de cara com um pneu",
  "Cuida bem do dogginho",
  "Literalmente a mulher mais perfeita do mundo",
  "Posta fancams mto foda",
  "Tem bom gosto para animes e séries",
  "Muito paciente (ainda joga genshin)",
  "Mãe de menina",
  "Sabe fazer doces oque é mto engraçado já que ela eh um BOMBOMZINHO",
  "Patenteou os melhores emojis (coração, demonho e morcego) simplesmente nn dá p não associar ela a esses emojos",
  "Meio que lembra um cachorrinho preto e isso é fofo",
  "Mistura os rock tudo em uma playlist só e isso autamicamente bota qualquer rockeiro chato pra mamar",
  "Gosta de esportes (coisa de gente maneira)",
  "Qualquer criança ia querer ser foda igual a ela quando crescer",
  "Parece uma escutura grega de tão linda é uma benção para os olhos",
  "Deixa as pessoas ao redor confortáveis com sua presença",
  "Tem um fone de ouvido muito aesthetic",
  "Low profile no insta isso é muito chique fodase",
  "MAD DOG AU AUA AUA UAU AU BARRK BARK AU AU",
  "Faz uns deliniados mto lindos eu vi ta no insta a prova",
  "É carismática e engraçada",
  "Consegue me entender mesmo quando acho que não estou falando nada com nada",
  "As vezes parece que estamos meio em sincronia, isso é divertido",
  "Tem a vibe de uma vampira que mora em um castelo bem trevoso e bebe sangue em um calice de ferro muito bucetônica",
  "Tem o sorriso mais lindo do mundo",
  "Tem os olhos da cor da tempestado que vem, castanhoooooooooosssss",
  "Enche o coração dos outros de orgulho, constantemente se esforça para construir a propria vida",
  "Toda vez que faz algo para mim, não importa se é bobo ou não, meu coração se derrete inteiro e preciso guardar ele dentro de um ponte",
  "Tem uma companhia tão agradável que me apeguei desde o primeiro momento que conheci (obrigada por puxar assunto comigo no xuitter)",
  "É divertido imaginar como seria dar um rolê com ela, espero q aconteça um dia",
  "É divertido ver ela surtar por algo que gosta no twitter, sempre me faz soltar ar pelo nariz",
  "Gosta de animais e isso é fofo",
  "Diva aesthetic",
  "Me deixa empolgada sempre que recebo uma mensagem dela",
  "Tem conselhos muito bons",
  "Sempre tenta trazer soluções para os problemas",
  "Sempre se prontifica a me ajudar, mesmo que eu não saiba como pedir por isso (mas sou sempre muito grata)",
  "É a melhor pessoa que conheci no ensino médio e sou muito grata por isso",
  "Não esqueceu de mim mesmo quando surtei e apaguei o xuitter sem explicações (me desculpe por isso)",
  "Me lembro dela sempre que olho para a lua, e me pergunto se ela tambem está olhando pára lua também",
  "Aposto que tem o cabelo cheiroso ela tem cara de xerosa",
  "Nunca reclama ou me xinga quando estou alucinada flodando a timeline com minha carência insuportavel (provando mais uma vez que é SIM uma pessoa paciênte)",
  "É muito boa em fazer os outros CORAR e ficar sem palavras (falo por experiência propia)",
  "Tem um ótimo gosto para tattoo com certeza vai virar uma gostosa tatuada um dia",
  "Tem bom gosto para piercings",
  "Tem bom gosto para escolher batons",
  "Tem um ótimo senso estético",
  "Escreve muuuito bem",
  "Consegue me fazer querer adiar minha morte alguns anos",
  "As vezes parece que somos almas gemeas pq nunca conheci ninguém que tivesse gostos que combinassem tanto com os meus kkkkkkk",
  "Consegue acordar cedo o que automaticamente faz dela uma pessoa foda !!!",
  "Fica linda quando posta foto no espelho da academia",
  "Ela me inspira tanto que me faz querer dobrar o mundo inteiro aos pés dela",
  "É gentil ao mesmo tempo que é forte e intensa",
  "Ela faz parecer que o certo é o universo girar em torno dela, porque nada além disso faria nenhum sentido",
  "É a mulher mais linda e inteligente do mundo e só minha opinião importa",
  "Ela sabe fazer incenso !! Eu sei eu já vi e acho mto cool da parte dela",
  "Ela sempre me manda videos fofos no instagram e me deixa boiola",
  "Simplesmente é impossível conhecer e Mei e ela não se tornar a sua pessoa favorita do mundo, seria o mesmo que não gostar do brilho da lua ou do cheiro de bolo recém assado",
];
